#!/bin/bash
TUSER=ubuntu
TUSERHOME=/home/${TUSER}
LAUNCHPAD_ID=$(config-get launchpad-id)

# Install needed packages
add-apt-repository multiverse
set -e
apt-get update

apt-get install -y python python-launchpadlib git lxc pastebinit apt-cacher-ng

# Create and set up my user and directories
if  ! id ${TUSER} ; then
    useradd -m -d ${TUSERHOME} ${TUSER}
fi

mkdir -p ${TUSERHOME}/.config
chown ${TUSER}:${TUSER} ${TUSERHOME}/.config

# Set up git global config to properly format commit msg
juju-log "Setting up git global config"
su - ubuntu -c "git config --global user.name 'PMR'"
su - ubuntu -c "git config --global user.email '<pmr@pmr-lander>'"

# Get pmr and my configuration to deploy
juju-log "Getting pmr configs from github"
[ -e ${TUSERHOME}/.config/pmr ] && rm -rf ${TUSERHOME}/.config/pmr || true
git clone git://github.com/checkbox/pmr-configs.git ${TUSERHOME}/.config/pmr

# Create the refresh_config.sh script
juju-log "Creating the refresh_config.sh script"
cat << EOF > ${TUSERHOME}/.config/pmr/refresh_config.sh
#!/bin/bash

git -C ${TUSERHOME}/.config/pmr pull
EOF
chmod +x ${TUSERHOME}/.config/pmr/refresh_config.sh

juju-log "Getting pmr from github"
[ -e ${TUSERHOME}/pmr ] && rm -rf ${TUSERHOME}/pmr || true
git clone git://github.com/checkbox/pmr.git ${TUSERHOME}/pmr

juju-log "Installing systemd unit file for pmr-lander"
cat << EOF > /lib/systemd/system/pmr-lander.service
[Unit]
Description=PMR instance (tarmac lander for git branches)

[Service]
User=${TUSER}
ExecStart=${TUSERHOME}/pmr/process-merge-requests --user=${LAUNCHPAD_ID} \
          --conf_file=${TUSERHOME}/.config/pmr/pmr.conf \
          --pre_exec=${TUSERHOME}/.config/pmr/refresh_config.sh \
          --credentials=${TUSERHOME}/.config/pmr/credentials
ExecReload=/bin/kill -HUP \$MAINPID
KillMode=process
Restart=on-failure
RestartSec=60s

[Install]
WantedBy=multi-user.target
EOF
